Add matrix build for targets providing tag prefix for distinct images
Remove extrenous 'file' from publish action

Remove duplicated linter action on pull requests from this repo

Debug buildkit

error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount412565048/Dockerfile: no such file or directory
Error: buildx failed with: error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount412565048/Dockerfile: no such file or directory

Specify platform linux/amd64

Debug /tmp/buildkit-mount* paths

Build base and cypress targets using matrix strategy

Limits to a single target at a time in the order that they are defined.
The concurrency is further limited by grouping using the commit sha

Do not fail the build during debug

Remove context

Add target as prefix to image tags

Add comment describing why context is not set